### ISSUE TITLE
[Question] Is it compliant with Rack?

### ISSUE THREAD

**Issue by ElMassimo** [digital-fabric/polyphony-http#2]
Hello, I was checking out [polyphony](https://github.com/digital-fabric/polyphony), which led me here.

I'd like to know if this server is intended to be compliant with [Rack](https://github.com/rack/rack), as it would be nice to experiment with polyphony to serve I/O-bound APIs 😃

**Comment by ciconia** [comment]
At the moment no, but eventually yes. That's one of the things I'm hoping to attack in the next few days.

**Comment by ElMassimo** [comment]
Happy to contribute, even if it's by providing a sample application.

**Comment by ciconia** [comment]
Have a look at [bin/poly](https://github.com/digital-fabric/polyphony-http/blob/master/bin/poly), it's the beginning of an Rack-based web server. The rack adapter is at [lib/polyphony/http/server/rack.rb](https://github.com/digital-fabric/polyphony-http/blob/master/lib/polyphony/http/server/rack.rb). Actually it's a bit more fleshed out than I remembered (it's been a while since I touched it), so feel free if you want to work on it...

**Comment by ElMassimo** [comment]
Looks like some files still depend on [`modulation`](https://github.com/digital-fabric/modulation).

Based on [this changelog entry](https://github.com/ElMassimo/polyphony-http/blob/master/CHANGELOG.md#L11), I'll go ahead and adapt these files to use a standard structure.

**Comment by ciconia** [comment]
Hey @ElMassimo just to give you a heads up - I intend to rename this gem and to extract all the HTTP-client stuff into a separate gem. I'll let you know when it's done...
